export const UPDATE_PLAYER_HAND_TOTAL = "UPDATE_PLAYER_HAND_TOTAL";
export const UPDATE_DEALER_HAND_TOTAL = "UPDATE_DEALER_HAND_TOTAL";
export const UPDATE_PLAYER_STAND_STATUS = "UPDATE_PLAYER_STAND_STATUS";